 language: python
 python:
    - "3.6"
 # command to install dependencies
 install:
   - pip install -r requirements.txt
   - python -m pip install -U selenium
 #  before_script: 
 # command to run tests
 script:
   - make test
   - make lint
  
